name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - trunk # Adjust to the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Match your project's Node.js version
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: ./tskd-api
        run: pnpm install

      # Step 5: Deploy using wrangler
      - name: Deploy to Cloudflare Workers
        working-directory: ./tskd-api
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: pnpm wrangler publish

